version: '3'

services:

  php:
    container_name: crud_app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./source:/source
    depends_on:
      - db

  nginx:
    container_name: crud_webserver
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./source:/source
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  db:
    container_name: crud_db
    image: mysql:8.0
    volumes:
      - /var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud
      MYSQL_USER: crud
      MYSQL_PASSWORD: secret

  migration:
    image: php:latest
    command: ["./wait-for-it.sh", "db:3306", "--", "echo", "db is up"]
    links:
      - db
    depends_on:
      - db