version: '3'

services:

  nginx:
    container_name: crud_webserver
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    container_name: crud_app
    build: php
    volumes:
      - ../source:/app
    depends_on:
      - db

  db:
    container_name: crud_db
    image: mysql:8.0
    volumes:
      - ./mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud
      MYSQL_USER: crud
      MYSQL_PASSWORD: secret